### ISSUE TITLE
compiler error: I/O error on .reds files

### ISSUE THREAD

**Issue by yanekyuk** [jac3km4/redscript-ide-vscode#1]
I cannot get it working on VSCode v1.63.2 on Windows.

Here is an error output when I hover over some redscript method:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:140:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 5:37:00 PM] Connection to server got closed. Server will restart.
[Error - 5:37:00 PM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
    at Object.dispose (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-languageclient\lib\common\client.js:73:35)
    at LanguageClient.handleConnectionClosed (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
    at LanguageClient.handleConnectionClosed (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-languageclient\lib\node\main.js:155:15)
    at closeHandler (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
    at CallbackList.invoke (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at closeHandler (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
    at CallbackList.invoke (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at StreamMessageReader.fireClose (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
    at Socket.<anonymous> (c:\Users\OMITTED\.vscode\extensions\jac3km4.redscript-ide-vscode-0.0.7\node_modules\vscode-jsonrpc\lib\common\messageReader.js:125:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
```

Should I run with `RUST_BACKTRACE=1` to get a more clear output? If so, how do I run with `RUST_BACKTRACE=1`?

**Comment by jac3km4** [comment]
have you set up the configuration?
```
"redscript.scriptCachePath": "D:\\path\\to\\r6\\cache\\final.redscripts.bk"
```
make sure it points at an existing file

**Comment by yanekyuk** [comment]
I am sure of it. I've tried removing `gameDir` and getting it working with only `scriptCachePath`, but no luck.

![resim](https://user-images.githubusercontent.com/26147025/149169170-0bffcebf-1eac-47aa-93d0-bf00652a9bc8.png)

**Comment by jac3km4** [comment]
can you upload the project that you're working on or some sample workspace that reproduces this issue?

**Comment by yanekyuk** [comment]
I am not working on a project, instead I am trying teach myself some redscript. Apparently, I've written a code so broken than it also broke the language server. 

I couldn't replicate this issue because I deleted that workspace. If I ever face the same issue, I will try to isolate the incident and reopen this issue or a new issue.

P.S. Starting from stratch with a new workspace, everything seems working right now.
